const VERSION="11.0.0",REPO="Taha8880/NowPulse",BRANCH="main",WORKER="src/worker.js",SITE="https://nowpulse.tavengers16.workers.dev",MODEL="@cf/zai-org/glm-4.7-flash";
const out=(x,s=200)=>new Response(JSON.stringify(x,null,2),{status:s,headers:{"content-type":"application/json","cache-control":"no-store"}});
const txt=x=>typeof x==="string"?x:(x?.response||x?.output_text||x?.choices?.[0]?.message?.content||"");
async function gh(env,path,init={}){if(!env.NOWPULSE_GITHUB_TOKEN)throw Error("NOWPULSE_GITHUB_TOKEN missing");const r=await fetch("https://api.github.com/repos/"+REPO+path,{...init,headers:{Authorization:"Bearer "+env.NOWPULSE_GITHUB_TOKEN,Accept:"application/vnd.github+json","X-GitHub-Api-Version":"2022-11-28","Content-Type":"application/json"}});const t=await r.text();let d={};try{d=t?JSON.parse(t):{}}catch{}if(!r.ok)throw Error("GitHub "+r.status+": "+(d.message||t.slice(0,300)));return d}
const dec=s=>{const b=atob(String(s).replace(/\s/g,"")),u=new Uint8Array(b.length);for(let i=0;i<b.length;i++)u[i]=b.charCodeAt(i);return new TextDecoder().decode(u)};
const enc=s=>{const b=new TextEncoder().encode(s);let x="";for(let i=0;i<b.length;i+=32768)x+=String.fromCharCode(...b.subarray(i,i+32768));return btoa(x)};
async function file(env,p){const d=await gh(env,"/contents/"+p+"?ref="+BRANCH);return{sha:d.sha,content:dec(d.content)}}
async function audit(){const paths=["/health","/api/news","/api/markets","/api/weather?city=cairo","/sitemap.xml"];const r=[];for(const p of paths){try{const x=await fetch(SITE+p);r.push({path:p,status:x.status,ok:x.ok})}catch(e){r.push({path:p,ok:false,error:String(e)})}}return r}
async function run(env){const checks=await audit(),bad=checks.filter(x=>!x.ok);if(!bad.length)return{ok:true,repairRequired:false,checks};if(!env.AI)return{ok:false,repairRequired:false,checks,reason:"AI binding unavailable"};const f=await file(env,WORKER);const prompt="You are the autonomous principal engineer for NowPulse. Diagnose only confirmed production failures. Return ONLY JSON with repair:boolean, reason:string, replacement:string. The replacement must be a complete src/worker.js. Preserve news, search, markets, articles, Arabic/English, RTL/LTR, SEO, AdSense and Created by Taha. Keep the critical HTTP path extremely light because Workers Free has a 10ms CPU request limit. Never invent data, secrets or unrelated features. Production checks:"+JSON.stringify(checks)+" SOURCE:"+f.content;const ans=txt(await env.AI.run(MODEL,{messages:[{role:"system",content:"Senior Cloudflare engineer. JSON only."},{role:"user",content:prompt}],temperature:0.05,max_completion_tokens:7000}));let p=null;try{p=JSON.parse(ans.replace(/^```json\s*/i,"").replace(/\s*```$/,"").trim())}catch{}if(!p?.repair||!p.replacement||p.replacement===f.content)return{ok:true,repairRequired:false,checks,reason:p?.reason||"No safe repair"};const branch="ai-repair/guardian-"+Date.now(),base=await gh(env,"/git/ref/heads/"+BRANCH);await gh(env,"/git/refs",{method:"POST",body:JSON.stringify({ref:"refs/heads/"+branch,sha:base.object.sha})});await gh(env,"/contents/"+WORKER,{method:"PUT",body:JSON.stringify({message:"NowPulse AI root-cause repair",content:enc(p.replacement),sha:f.sha,branch})});const pr=await gh(env,"/pulls",{method:"POST",body:JSON.stringify({title:"NowPulse AI root-cause repair",head:branch,base:BRANCH,body:"Autonomous repair created after production evidence. Existing validation gates remain required."})});return{ok:true,repairRequired:true,checks,branch,pr:pr.html_url,reason:p.reason}}
export default{async fetch(req,env){const p=new URL(req.url).pathname;if(p==="/health")return out({ok:true,service:"NowPulse AI Manager",version:VERSION,github:!!env.NOWPULSE_GITHUB_TOKEN,ai:!!env.AI,mode:env.NOWPULSE_AI_REPAIR_MODE||"auto"});if(p==="/repair"){try{return out(await run(env))}catch(e){return out({ok:false,error:String(e?.message||e)},500)}}return out({ok:true,service:"NowPulse AI Manager",version:VERSION,endpoints:["/health","/repair"]})},async scheduled(e,env,ctx){ctx.waitUntil(run(env).catch(e=>console.error("AI maintenance failed",e)))}};